baseurl = "https://mkeskisa.netlify.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Stuff by me"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  logo = "img/pusheen2.png"
  favicon = "img/pusheen2.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Markus Keski-Säntti"
  email = "markuskeskisantti@gmail.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    identifier = "Archive"
    name = "Archive"
    weight = 3

[[menu.main]]
    parent = "Archive"
    name = "Fast sankey diagrams"
    url = "archive/article_3.html"
    weight = 1

[[menu.main]]
    parent = "Archive"
    name = "CS:GO Roundtime analysis"
    url = "archive/article_1.html"
    weight = 2

[[menu.main]]
    parent = "Archive"
    name = "Forecasting round winner"
    url = "archive/article_2.html"
    weight = 3